name: Build and Compile .NET Project
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Compile
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 2.0.0 # Replace with the desired version
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build project
      run: dotnet build --configuration Release
